import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docusaurus: [
    {
      type: 'category',
      label: 'Tutorial - Basics',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],

  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/python',
    },
  ],
  cSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/c',
    },
  ],
  cppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/cpp',
    },
  ],
  goSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/go',
    },
  ],
  jsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/js',
    },
  ],
  luaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/lua',
    },
  ],
  aiBasicSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/基础',
    },],

  yoloSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/yolo',
    },],
  aiProjectSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/项目',
    },],
  aiModelSidebr: [
    {
      type: 'autogenerated',
      dirName: 'ai/其他模型',
    },],
  dinoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/DINO',
    },],
  samSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/SAM',
    },],
  stablediffusionSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/stable-diffusion',
    },],
  transformerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai/transformer',
    },],
  algoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'algo/通用算法',
    },
    {
      type: 'autogenerated',
      dirName: 'algo/图像算法',
    },
  ],
};

export default sidebars;