import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docusaurus: [
    {
      type: 'category',
      label: 'Tutorial - Basics',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],

  pythonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/python',
    },
  ],
  cSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/c',
    },
  ],
  cppSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/cpp',
    },
  ],
  goSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/go',
    },
  ],
  jsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/js',
    },
  ],
  luaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'language/lua',
    },
  ],
  aiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'ai',
    },
  ],
  algoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'algo',
    },
  ],
};

export default sidebars;